ltc_article_category_view:
    pattern:  /{slug}
    defaults: { _controller: LtcArticle:Category:view }

ltc_article_article_view:
    pattern:  /{categorySlug}/{slug}
    defaults: { _controller: LtcArticle:Article:view }
