ltc_article_admin_category_view:
    pattern:  /{slug}
    defaults: { _controller: LtcArticle:CategoryAdmin:view }

ltc_article_admin_article_view:
    pattern:  /{categorySlug}/{slug}
    defaults: { _controller: LtcArticle:ArticleAdmin:view }
