imports:
    - { resource: imagine.yml }
    - { resource: elastica.yml }
    - { resource: config_local.yml }

framework:
    charset:       UTF-8
    #secret: see config local
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enable_annotations: true }
    templating:    { engines: ['twig'], assets_version: 3 }
    form:          true
    session:
        default_locale: fr
        lifetime:       136000
        auto_start:     true

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                persist: ltc
    default_database: ltc_%kernel.environment%
    document_managers:
        default:
            metadata_cache_driver: apc
            mappings:
                FOSUserBundle:
                FOSCommentBundle:
                StofDoctrineExtensionsBundle:
                LtcUserBundle:
                LtcCommentBundle:
                LtcDocBundle:
                LtcArticleBundle:
                LtcBlogBundle:
                LtcImageBundle:
                LtcTagBundle:
                LtcStoryBundle:
                LtcConfigBundle:

stof_doctrine_extensions:
    mongodb:
        default:
            sluggable: true
            translatable: false
            timestampable: true
            loggable: false
            tree: false

security:
    role_hierarchy:
        ROLE_SUPERADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_BACKEND]
    providers:
        fos_user_provider:
            id: fos_user.user_manager
    firewalls:
        main:
            form_login:
                provider:    fos_user_provider
                login_path:  /login
                check_path:  /login_check
                use_referer: false
                default_target_path: /admin
            remember_me:
                key:  kRopAjYEwDza74
                name: ltc_remember_me
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout: true
            anonymous: true
    access_control:
        - { path: "^/admin", role: ROLE_BACKEND }

fos_user:
    db_driver: mongodb
    firewall_name: main
    class:
        model:
            user: Ltc\UserBundle\Document\User
    service:
        mailer: fos_user.mailer.noop

fos_comment:
    db_driver: mongodb
    class:
        model:
            comment: Ltc\CommentBundle\Document\Comment
    service:
        form_factory:
            comment: ltc_comment.form_factory.comment
        spam_detection:
            comment: fos_comment.spam_detection.comment.akismet
    akismet:
        url: http://esmeree.fr/
        #api_key: see config local

apc:
    #host: see config local
    web_dir: %kernel.root_dir%/../web

knplabs_menu:
    twig: true

knplabs_markdown:
    parser:
        service: markdown.parser.medium

ltc_image:
    upload_dir: %kernel.root_dir%/../web/uploads

ltc_config:
    author:
        model: Ltc\ConfigBundle\Document\Author
        form:  Ltc\ConfigBundle\Form\AuthorForm
        title: Auteur
        form_type: ltc_config.form_type.author
    photo:
        model: Ltc\ConfigBundle\Document\Photo
        form:  Ltc\ConfigBundle\Form\PhotoForm
        title: Ailleurs
        form_type: ltc_config.form_type.photo
    featured_story:
        model: Ltc\ConfigBundle\Document\FeaturedStory
        form:  Ltc\ConfigBundle\Form\FeaturedStoryForm
        title: Actu Accueil
        form_type: ltc_config.form_type.featured_story
    featured_article:
        model: Ltc\ConfigBundle\Document\FeaturedArticle
        form:  Ltc\ConfigBundle\Form\FeaturedArticleForm
        title: A propos de...
        form_type: ltc_config.form_type.featured_article

zend_cache:
    templates:
        ltc_article.provider:
            frontendBackendAutoload: true
            frontend:
                name: Core
                options:
                    lifetime: 99999999
                    automatic_serialization: true
            backend:
                name: Apc
