framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        #secret: see_config_local
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] }
    document_root: %kernel.root_dir%/../web
    #assets_version: 1
    session:
        default_locale: fr
        lifetime:       36000
        auto_start:     true

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false

avalanche_imagine:
    web_root:     %kernel.root_dir%/../web
    cache_prefix: imagine
    driver:       gd
    filters:
        admin_medium:
            type:    thumbnail
            options: { size: [200, 150], mode: inset }
        admin_small:
            type:    thumbnail
            options: { size: [100, 50], mode: inset }

doctrine_mongo_db:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                persist: ltc
    default_database: ltc_%kernel.environment%
    document_managers:
        default:
            metadata_cache_driver: apc
            mappings:
                FOSUser:
                FOSComment:
                StofDoctrineExtensions:
                LtcUser:
                LtcDoc:
                LtcArticle:
                LtcBlog:
                LtcPackage:
                LtcImage:
                LtcTag:

stof_doctrine_extensions:
    mongodb:
        default:
            sluggable: true
            translatable: false
            timestampable: true
            loggable: false
            tree: false

security:
    role_hierarchy:
        ROLE_SUPERADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_BACKEND]
    providers:
        fos_user_provider:
            id: fos_user.user_manager
    firewalls:
        main:
            form_login:
                provider:    fos_user_provider
                login_path:  /login
                check_path:  /login_check
                use_referer: false
                default_target_path: /admin
            remember_me:
                key:  kRopAjYEwDza74
                name: ltc_remember_me
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout: true
            anonymous: true
    access_control:
        - { path: "^/admin", role: ROLE_BACKEND }

fos_user:
    db_driver: mongodb
    firewall_name: main
    class:
        model:
            user: Ltc\UserBundle\Document\User

fos_comment:
    db_driver: mongodb
    class:
        model:
            comment: FOS\CommentBundle\Document\Comment

apc:
    host: http://ltc
    web_dir: %kernel.root_dir%/../web

knplabs_menu:
    twig: true

ltc_image:
    upload_dir: %kernel.root_dir%/../web/uploads

imports:
    - { resource: config_local.yml }
