imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

#assetic:
    #use_controller: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: info

jms_debugging:
    # You can set this to true if you want to automatically retrieve help 
    # messages for public exceptions. If you leave this set to false, you have
    # to click the "search" button manually each time.
    auto_help: false
