imports:
    - { resource: imagine.yml }
    - { resource: elastica.yml }
    - { resource: user.yml }
    - { resource: security.yml }
    - { resource: doctrine.yml }
    - { resource: assetic.yml }
    - { resource: comment.yml }
    - { resource: gaufrette.yml }
    - { resource: akismet.yml }
    - { resource: ltc.yml }
    - { resource: config_local.yml }

framework:
    charset:       UTF-8
    #secret: see config local
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enable_annotations: true }
    templating:    { engines: ['twig'], assets_version: 4 }
    form:          true
    session:
        default_locale: fr
        lifetime:       136000
        auto_start:     true
        name:     ltc2
    translator: { fallback: fr }

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: warning

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

apc:
    #host: see config local
    web_dir: %kernel.root_dir%/../web

knplabs_menu:
    twig: true

ornicar_insane_markdown:
    path: /usr/local/bin/markdown
