imports:
    - { resource: imagine.yml }
    - { resource: elastica.yml }
    - { resource: user.yml }
    - { resource: security.yml }
    - { resource: doctrine.yml }
    - { resource: comment.yml }
    - { resource: zend.yml }
    - { resource: ltc.yml }
    - { resource: config_local.yml }

framework:
    charset:       UTF-8
    #secret: see config local
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enable_annotations: true }
    templating:    { engines: ['twig'], assets_version: 3 }
    form:          true
    session:
        default_locale: fr
        lifetime:       136000
        auto_start:     true

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

apc:
    #host: see config local
    web_dir: %kernel.root_dir%/../web

knplabs_menu:
    twig: true

knplabs_markdown:
    parser:
        service: markdown.parser.medium
