foq_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    default_client: default
    indexes:
        doc:
            client: default
            types:
                blog:
                    mappings:
                        title: { boost: 8 }
                        summary: { boost: 2 }
                        body: 
                        tagsAsString: { boost: 3 }
                        authorName: 
                        authorBio: 
                        reference:
                article:
                    mappings:
                        title: { boost: 8 }
                        categoryTitle: { boost: 2 }
                        summary: { boost: 2 }
                        body: 
                        tagsAsString: { boost: 3 }
                        authorName: 
                        authorBio: 
                        reference:
    default_index: doc
