foq_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    default_client: default
    indexes:
        doc:
            client: default
            type_prototype:
                doctrine:
                    driver: mongodb
                    provider:
                    finder:
                    listener:
            settings: 
                index: 
                    analysis: 
                        analyzer: 
                            my_analyzer: 
                                type: custom
                                tokenizer: lowercase
                                filter   : [my_ngram]
                        filter: 
                            my_ngram: 
                                type: "nGram"
                                min_gram: 3
                                max_gram: 5
            types:
                blog:
                    doctrine:
                        model: Ltc\BlogBundle\Document\BlogEntry
                        provider:
                            query_builder_method: createPublishedQueryBuilder
                    mappings:
                        title: { boost: 8, analyzer: my_analyzer }
                        slug: { boost: 8, analyzer: my_analyzer }
                        summary: { boost: 2, analyzer: my_analyzer }
                        body: { boost: 1, analyzer: my_analyzer }
                        tags: { boost: 4 }
                        authorName: 
                        authorBio: 
                        reference:
                article:
                    doctrine:
                        model: Ltc\ArticleBundle\Document\Article
                        provider:
                            query_builder_method: createPublishedQueryBuilder
                    mappings:
                        title: { boost: 8, analyzer: my_analyzer }
                        slug: { boost: 8, analyzer: my_analyzer }
                        categoryTitle: { boost: 2, analyzer: my_analyzer }
                        summary: { boost: 2, analyzer: my_analyzer }
                        body: { boost: 1, analyzer: my_analyzer }
                        tags: { boost: 4 }
                        authorName: 
                        authorBio: 
                        reference:
    default_index: doc
