foq_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    default_client: default
    indexes:
        doc:
            client: default
            types:
                blog:
                    doctrine:
                        driver: mongodb
                        model: Ltc\BlogBundle\Document\BlogEntry
                        provider:
                            query_builder_method: createPublishedQueryBuilder
                    mappings:
                        title: { boost: 8 }
                        summary: { boost: 2 }
                        body: 
                        tags: { boost: 4 }
                        authorName: 
                        authorBio: 
                        reference:
                article:
                    doctrine:
                        driver: mongodb
                        model: Ltc\ArticleBundle\Document\Article
                        provider:
                            query_builder_method: createPublishedQueryBuilder
                    mappings:
                        title: { boost: 8 }
                        categoryTitle: { boost: 2 }
                        summary: { boost: 2 }
                        body: 
                        tags: { boost: 4 }
                        authorName: 
                        authorBio: 
                        reference:
    default_index: doc
