ltc_config:
    author:
        model: Ltc\ConfigBundle\Document\Author
        form_type: ltc_config.form_type.author
        title: Auteur
    photo:
        model: Ltc\ConfigBundle\Document\Photo
        form_type: ltc_config.form_type.photo
        title: Ailleurs
    featured_story:
        model: Ltc\ConfigBundle\Document\FeaturedStory
        form_type: ltc_config.form_type.featured_story
        title: Actu Accueil
    featured_article:
        model: Ltc\ConfigBundle\Document\FeaturedArticle
        form_type: ltc_config.form_type.featured_article
        title: A propos de...

ltc_file:
    filesystem_web_path:
        files: /uploads/file
        images: /uploads/image
