ltc_core:
    resource: "@LtcCore/Resources/config/routing.yml"

ltc_admin:
    resource: "@LtcAdmin/Resources/config/routing.yml"
    prefix: /admin

ltc_article_admin:
    resource: "@LtcArticle/Resources/config/routing_admin.yml"
    prefix: /admin/articles

ltc_tag_admin:
    resource: "@LtcTag/Resources/config/routing_admin.yml"
    prefix: /admin/tags

fos_user_user:
    resource: "@FOSUser/Resources/config/routing/user.xml"
    prefix: /user

fos_user_security:
    resource: "@FOSUser/Resources/config/routing/security.xml"

 _imagine:
    resource: .
    type:     imagine
