ltc_core:
    resource: "@LtcCoreBundle/Resources/config/routing.yml"

ltc_admin:
    resource: "@LtcAdminBundle/Resources/config/routing.yml"
    prefix: /admin

ltc_article_admin:
    resource: "@LtcArticleBundle/Resources/config/routing_admin.yml"
    prefix: /admin/articles

ltc_blog:
    resource: "@LtcBlogBundle/Resources/config/routing.yml"
    prefix: /table-ronde

ltc_blog_admin:
    resource: "@LtcBlogBundle/Resources/config/routing_admin.yml"
    prefix: /admin/table-ronde

ltc_tag:
    resource: "@LtcTagBundle/Resources/config/routing.yml"
    prefix: /tags

ltc_tag_admin:
    resource: "@LtcTagBundle/Resources/config/routing_admin.yml"
    prefix: /admin/tags

ltc_story_admin:
    resource: "@LtcStoryBundle/Resources/config/routing_admin.yml"
    prefix: /admin/actus

ltc_config_admin:
    resource: "@LtcConfigBundle/Resources/config/routing_admin.yml"
    prefix: /admin/config

fos_user_user:
    resource: "@FOSUserBundle/Resources/config/routing/user.xml"
    prefix: /user

fos_comment:
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /comment

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

ltc_compat_doc:
    resource: "@LtcCompatBundle/Resources/config/routing.yml"

ltc_article:
    resource: "@LtcArticleBundle/Resources/config/routing.yml"

_imagine:
    resource: .
    type:     imagine
