security:
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_BACKEND]
    providers:
        fos_user_provider:
            id: fos_user.user_manager
    firewalls:
        main:
            form_login:
                provider:    fos_user_provider
                login_path:  /login
                check_path:  /login_check
                use_referer: false
                default_target_path: /admin
            remember_me:
                key:  kRopAjYEwDza74
                name: ltc_remember_me
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout: true
            anonymous: true
    access_control:
        - { path: "^/admin", role: ROLE_BACKEND }
