ltc_tag_admin_index:
    pattern:  /
    defaults: { _controller: LtcTagBundle:Admin:index }
ltc_tag_admin_list:
    pattern: /list.{_format}
    defaults: { _controller: LtcTagBundle:Admin:list, _format: json }
    requirements: { _format: json }
