ltc_compat_author:
    pattern: /pascal-duplessis
    defaults: { _controller: LtcCompatBundle:Compat:route, redirect_route: ltc_author }
ltc_compat_idoc:
    pattern: /idoc
    defaults: { _controller: LtcCompatBundle:Compat:route, redirect_route: homepage }
