homepage:
    pattern:  /
    defaults: { _controller: LtcCore:Main:index }

ltc_archive:
    pattern:  /archives
    defaults: { _controller: LtcCore:Main:archive }

ltc_author:
    pattern:  /auteur
    defaults: { _controller: LtcCore:Main:author }

ltc_feed:
    pattern:  /atom.xml
    defaults: { _controller: LtcCore:Main:feed, _format: xml }
