ltc_admin_dashboard:
    pattern:  /
    defaults: { _controller: LtcAdminBundle:Dashboard:index }
ltc_admin_manager:
    pattern:  /manager
    defaults: { _controller: LtcAdminBundle:Dashboard:manager }
